import json
import subprocess
import sys
import time
from copy import deepcopy
from functools import lru_cache
from http.client import HTTPConnection
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from bas_metadata_library.standards.magic_administration.v1 import AdministrationMetadata
from bas_metadata_library.standards.magic_administration.v1.utils import AdministrationKeys, set_admin
from lantern.lib.metadata_library.models.record.presets.admin import OPEN_ACCESS
from lantern.models.record.const import CATALOGUE_NAMESPACE

from tests.resources.admin_keys import test_keys
from zap.utils import load_secrets

if TYPE_CHECKING:
    from collections.abc import Generator


@pytest.fixture()
def fx_record_config_iso_minish() -> dict:
    """Minimal record configuration, plus file identifier and hierarchy level."""
    return {
        "file_identifier": "x",
        "hierarchy_level": "product",
        "metadata": {
            "contacts": [{"organisation": {"name": "x"}, "role": ["pointOfContact"]}],
            "date_stamp": "2014-06-30",
        },
        "identification": {
            "title": {"value": "x"},
            "dates": {"creation": "2014-06-30"},
            "abstract": "x",
            "language": "eng",
        },
    }


@pytest.fixture()
def fx_record_config_cat_min(fx_record_config_iso_minish: dict) -> dict:
    """Minimal record configuration for an ItemCatalogue model."""
    config = deepcopy(fx_record_config_iso_minish)
    config["identification"]["identifiers"] = [
        {
            "identifier": config["file_identifier"],
            "href": f"https://{CATALOGUE_NAMESPACE}/items/{config['file_identifier']}",
            "namespace": CATALOGUE_NAMESPACE,
        }
    ]
    config["identification"]["contacts"] = [{**deepcopy(config["metadata"]["contacts"][0]), "email": "x"}]

    return config


@pytest.fixture()
def fx_record_config_magic(fx_admin_meta_keys: AdministrationKeys, fx_record_config_cat_min: dict) -> dict:
    """
    Valid record configuration for a record complying with MAGIC discovery and administration profiles.

    Generated by dumping config generated with `zap.records._make_base_record()`, replacing file identifier references
    and removing admin metadata. Then recreating admin metadata with test keys and updated file identifier.
    """
    config = {
        "file_identifier": fx_record_config_cat_min["file_identifier"],
        "hierarchy_level": "product",
        "metadata": {
            "character_set": "utf8",
            "language": "eng",
            "contacts": [
                {
                    "organisation": {
                        "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
                        "href": "https://ror.org/01rhff309",
                        "title": "ror",
                    },
                    "phone": "+44 (0)1223 221400",
                    "address": {
                        "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
                        "city": "Cambridge",
                        "administrative_area": "Cambridgeshire",
                        "postal_code": "CB3 0ET",
                        "country": "United Kingdom",
                    },
                    "email": "magic@bas.ac.uk",
                    "online_resource": {
                        "href": "https://www.bas.ac.uk/teams/magic",
                        "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
                        "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
                        "function": "information",
                    },
                    "role": ["pointOfContact"],
                }
            ],
            "constraints": [
                {"type": "access", "restriction_code": "unrestricted", "statement": "Open Access (Anonymous)"},
                {
                    "type": "usage",
                    "restriction_code": "license",
                    "statement": "This information is licensed under the Creative Commons Attribution-NoDerivatives 4.0 International Licence (CC BY-ND 4.0). To view this licence, visit https://creativecommons.org/licenses/by-nd/4.0/",
                    "href": "https://creativecommons.org/licenses/by-nd/4.0/",
                },
            ],
            "maintenance": {"maintenance_frequency": "asNeeded", "progress": "completed"},
            "date_stamp": "2026-08-09",
            "metadata_standard": {
                "name": "ISO 19115-2 Geographic Information - Metadata - Part 2: Extensions for Imagery and Gridded Data",
                "version": "ISO 19115-2:2009(E)",
            },
        },
        "identification": {
            "title": {"value": "..."},
            "abstract": "...",
            "dates": {"creation": "2026-08-09T12:40:11+00:00"},
            "edition": "1",
            "other_citation_details": f"British Antarctic Survey (?year). _..._ (Version 1) [Product]. British Antarctic Survey Mapping and Geographic Information Centre. [https://data.bas.ac.uk/items/{fx_record_config_cat_min['file_identifier']}](https://data.bas.ac.uk/items/{fx_record_config_cat_min['file_identifier']}).",
            "identifiers": [
                {
                    "identifier": fx_record_config_cat_min["file_identifier"],
                    "href": f"https://lantern.data.bas.ac.uk/items/{fx_record_config_cat_min['file_identifier']}",
                    "namespace": "lantern.data.bas.ac.uk",
                }
            ],
            "contacts": [
                {
                    "organisation": {
                        "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
                        "href": "https://ror.org/01rhff309",
                        "title": "ror",
                    },
                    "phone": "+44 (0)1223 221400",
                    "address": {
                        "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
                        "city": "Cambridge",
                        "administrative_area": "Cambridgeshire",
                        "postal_code": "CB3 0ET",
                        "country": "United Kingdom",
                    },
                    "email": "magic@bas.ac.uk",
                    "online_resource": {
                        "href": "https://www.bas.ac.uk/teams/magic",
                        "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
                        "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
                        "function": "information",
                    },
                    "role": ["pointOfContact", "publisher"],
                },
                {
                    "organisation": {
                        "name": "UK Research and Innovation",
                        "href": "https://ror.org/001aqnf71",
                        "title": "ror",
                    },
                    "address": {
                        "delivery_point": "Polaris House",
                        "city": "Swindon",
                        "postal_code": "SN2 1FL",
                        "country": "United Kingdom",
                    },
                    "online_resource": {
                        "href": "https://www.ukri.org",
                        "title": "UKRI - UK Research and Innovation",
                        "description": "Corporate website for UK Research and Innovation (UKRI).",
                        "function": "information",
                    },
                    "role": ["rightsHolder"],
                },
            ],
            "maintenance": {"maintenance_frequency": "asNeeded", "progress": "completed"},
            "constraints": [
                {"type": "access", "restriction_code": "unrestricted", "statement": "Open Access (Anonymous)"},
                {
                    "type": "usage",
                    "restriction_code": "license",
                    "statement": "This information is licensed under the Open Government Licence v3.0. To view this licence, visit https://www.nationalarchives.gov.uk/doc/open-government-licence/.",
                    "href": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
                },
            ],
            "character_set": "utf8",
            "language": "eng",
            "extents": [
                {
                    "identifier": "bounding",
                    "geographic": {
                        "bounding_box": {
                            "west_longitude": 0,
                            "east_longitude": 0,
                            "south_latitude": 0,
                            "north_latitude": 0,
                        }
                    },
                }
            ],
            "lineage": {"statement": "..."},
            "domain_consistency": [
                {
                    "specification": {
                        "dates": {"publication": "2025-11-24"},
                        "edition": "2",
                        "title": {
                            "value": "British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Discovery Metadata Profile",
                            "href": "https://metadata-standards.data.bas.ac.uk/profiles/magic-discovery/v2/",
                        },
                        "contact": {
                            "organisation": {
                                "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
                                "href": "https://ror.org/01rhff309",
                                "title": "ror",
                            },
                            "phone": "+44 (0)1223 221400",
                            "address": {
                                "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
                                "city": "Cambridge",
                                "administrative_area": "Cambridgeshire",
                                "postal_code": "CB3 0ET",
                                "country": "United Kingdom",
                            },
                            "email": "magic@bas.ac.uk",
                            "online_resource": {
                                "href": "https://www.bas.ac.uk/teams/magic",
                                "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
                                "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
                                "function": "information",
                            },
                            "role": ["publisher"],
                        },
                    },
                    "explanation": "Resource within scope of the British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Discovery Metadata Profile.",
                    "result": True,
                },
                {
                    "specification": {
                        "dates": {"publication": "2025-10-22"},
                        "edition": "1",
                        "title": {
                            "value": "British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Administration Metadata Profile",
                            "href": "https://metadata-standards.data.bas.ac.uk/profiles/magic-administration/v1/",
                        },
                        "contact": {
                            "organisation": {
                                "name": "Mapping and Geographic Information Centre, British Antarctic Survey",
                                "href": "https://ror.org/01rhff309",
                                "title": "ror",
                            },
                            "phone": "+44 (0)1223 221400",
                            "address": {
                                "delivery_point": "British Antarctic Survey, High Cross, Madingley Road",
                                "city": "Cambridge",
                                "administrative_area": "Cambridgeshire",
                                "postal_code": "CB3 0ET",
                                "country": "United Kingdom",
                            },
                            "email": "magic@bas.ac.uk",
                            "online_resource": {
                                "href": "https://www.bas.ac.uk/teams/magic",
                                "title": "Mapping and Geographic Information Centre (MAGIC) - BAS public website",
                                "description": "General information about the BAS Mapping and Geographic Information Centre (MAGIC) from the British Antarctic Survey (BAS) public website.",
                                "function": "information",
                            },
                            "role": ["publisher"],
                        },
                    },
                    "explanation": "Resource within scope of the British Antarctic Survey (BAS) Mapping and Geographic Information Centre (MAGIC) Administration Metadata Profile.",
                    "result": True,
                },
            ],
        },
    }
    admin_meta = AdministrationMetadata(id=config["file_identifier"])
    admin_meta.metadata_permissions = [OPEN_ACCESS]
    admin_meta.resource_permissions = [OPEN_ACCESS]
    set_admin(keys=fx_admin_meta_keys, config=config, admin_meta=admin_meta)
    return config


@lru_cache(maxsize=1)
def _admin_meta_keys() -> AdministrationKeys:
    """
    BAS Metadata Library administration metadata test encryption and signing keys.

    These test keys are not secret and so not sensitive.

    Standalone method to allow use outside of fixtures in test parametrisation.

    Cached for better performance.
    """
    return test_keys()


def add_min_admin_meta(config: dict) -> None:
    """Add minimal administration metadata to a record config inplace."""
    set_admin(
        keys=_admin_meta_keys(),
        config=config,
        admin_meta=AdministrationMetadata(id=config["file_identifier"]),
    )


@pytest.fixture()
def fx_admin_meta_keys() -> AdministrationKeys:
    """Administration keys for signing and encrypting administrative metadata."""
    return _admin_meta_keys()


def _get_test_record_path(name: str) -> Path:
    """Get the path to a record config file from test resources."""
    return Path(__file__).parent.parent / "tests" / "resources" / "records" / name


@pytest.fixture(scope="session")
def fx_app_port() -> int:
    """
    Port for Streamlit test server.

    Avoids Streamlit default port (8501) to prevent conflict with non-test instances.
    """
    return 8502


@pytest.fixture(scope="session")
def fx_app_url(fx_app_port: int) -> str:
    """URL for Streamlit test server."""
    return f"http://localhost:{fx_app_port}"


@pytest.fixture(scope="session")
def fx_app(fx_app_port: int) -> Generator:
    """
    Run Streamlit app for Playwright e2e tests.

    Spawns a subprocess running the app on a custom port with secrets set by pytest-env.
    """
    runner_script = Path(__file__).parent / "scripts" / "run_app.py"
    secrets = json.dumps(load_secrets(read_dotenv=False))  # ignore dot-env

    # Start the app process
    process = subprocess.Popen(  # noqa: S603
        [
            sys.executable,
            str(runner_script),
            str(fx_app_port),
            secrets,
        ],
    )

    # Wait for server to be ready
    retries = 3
    while retries > 0:
        try:
            conn = HTTPConnection(f"localhost:{fx_app_port}")
            conn.request("HEAD", "/")
            response = conn.getresponse()
            if response is not None:
                break
        except ConnectionRefusedError, OSError:
            time.sleep(1)
            retries -= 1
    if not retries:
        process.terminate()
        msg = "Failed to start Streamlit server"
        raise RuntimeError(msg) from None

    yield

    process.terminate()
    process.wait(timeout=5)
